version: '3.9'

services:

  nodejs:
    container_name: nodejs
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres
    networks:
      - app-connect
    ports:
      - '3333:3333'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DB=fretech
      - NODE_ENV=prod
      - API_PORT=3333

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fretech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - app-connect

networks:
  app-connect:
      driver: bridge
